# Generated by Django 3.2 on 2023-06-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_yamdbuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='password',
        ),
        migrations.AddField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
