# Generated by Django 3.2 on 2023-06-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_yamdbuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='role',
            field=models.CharField(blank=True, choices=[('U', 'user'), ('M', 'moderator'), ('A', 'admin')], default='user', max_length=1, null=True),
        ),
    ]
